name: C
permissions:
  contents: read

on:
  push:
    branches:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} / ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        cc:
          - gcc
          - clang

        include:
          - os: macos-latest
            cc: clang

    env:
      CC: ${{ matrix.cc }}
      CFLAGS: -Wall -Wextra -Werror

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: ${{ matrix.install }}

    - name: Bootstrap nob
      run: $CC $CFLAGS -o nob nob.c

    - name: Build
      run: ./nob

    - name: Run Tests
      run: ./nob test

  build-windows:
    name: "windows-latest / cl"
    runs-on: windows-latest

    env:
      CC: cl

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Bootstrap nob
      run: cl /nologo /Fe:nob nob.c

    - name: Build
      run: ./nob

    - name: Run Tests
      run: ./nob test
